[mgr]
append_keymap = [
  { on = [
    "g",
    "m",
  ], run = "cd /run/media/nicknamely/", desc = "Go to /run/media/nicknamely" },

  { on = [
    "g",
    "p",
  ], run = "cd ~/Projects/", desc = "Go to ~/Projects/" },

  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },

  { on = "<C-y>", run = [
    'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
    "yank",
  ], desc = "Copy to clipboard" },

  { on = "<C-m>", run = [
    '''shell -- paths=$(for p in "$@"; do echo "$p"; done | paste -s -d,) thunderbird -compose "attachment='$paths'" ''',
  ], desc = "mail to " },

  { on = "M", run = "plugin toggle-pane max-preview", desc = "Maximize preview" },

  { on = "<C-g>", run = '''shell --block 'lazygit' ''', desc = "Open lazygit inside folder" },
]

# { on = [
#   "g",
#   "r",
# ], run = 'shell ya emit cd "$(git rev-parse --show-toplevel)"' },
